// Flow 206 — the filter, and the wall around what it produces.
//
// `review-learn-cli.test.ts` next door runs the whole loop from GitHub fixtures
// to a written `SKILL.md`, which is the only test that can see whether the join
// exists. This file covers the two things that loop cannot show from the outside:
// the shape of the filter at its edges, and the containment guarantee — which is
// a REFUSAL, and a refusal never happens on a healthy path.

import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { expect, test } from "bun:test";
import { applyLearningProposal, type LearningProposal } from "../gdskills/learn";
import { loadReviewLearningConfig, learningSourceLessons, selectLearnableComments } from "./review-learning";
import type { SeenComment } from "./pr-comments";

function seen(author: string, body: string | undefined, id = author): SeenComment {
  const comment: SeenComment = {
    id,
    thread_id: null,
    author,
    url: `https://github.com/o/r/pull/7#discussion_${id}`,
    first_seen_round: 1,
    last_seen_round: 1,
    submitted_at: "2026-08-30T00:00:00Z",
  };
  if (body !== undefined) comment.body = body;
  return comment;
}

// --- the filter --------------------------------------------------------------

test("only configured authors are kept, and the rest are counted rather than dropped silently", () => {
  const selection = selectLearnableComments(
    { seen: [seen("named", "This is a lesson worth keeping."), seen("stranger", "This is not.")] },
    ["named"],
  );

  expect(selection.kept.map((c) => c.author)).toEqual(["named"]);
  expect(selection.unconfigured.map((c) => c.author)).toEqual(["stranger"]);
});

test("author matching is case-insensitive, because GitHub logins are", () => {
  const selection = selectLearnableComments({ seen: [seen("NamedReviewer", "A lesson body here.")] }, ["namedreviewer"]);
  expect(selection.kept).toHaveLength(1);
});

test("author matching is exact — a prefix of a configured login is a different person", () => {
  // "no prefix match, no contains" is a claim the module makes; without this it
  // would be a comment. `named` configured must not admit `named-bot`.
  const selection = selectLearnableComments({ seen: [seen("named-bot", "A lesson body here.")] }, ["named"]);
  expect(selection.kept).toEqual([]);
  expect(selection.unconfigured).toHaveLength(1);
});

test("a configured author whose comment has no recorded body is reported, not read as silence", () => {
  // Records written before the body field existed. Learning nothing from them is
  // right; learning an empty lesson from them is not, and neither is pretending
  // they were never there.
  const selection = selectLearnableComments({ seen: [seen("named", undefined)] }, ["named"]);
  expect(selection.kept).toEqual([]);
  expect(selection.bodyless).toHaveLength(1);
  expect(selection.unconfigured).toEqual([]);
});

// --- the rendering the extractor reads ---------------------------------------

test("a long comment is split into sentences, so the points past the first 260 characters survive", () => {
  // The record stores up to 800 characters and the extractor drops any string
  // over 260. Passed whole, a considered review comment is truncated to its
  // opening and everything after it is lost — the longer and more careful the
  // comment, the more of it disappears.
  //
  // Asserting only "every lesson is under 260 characters" does NOT pin this: a
  // single hard truncation satisfies it too. What distinguishes splitting from
  // clipping is whether the LAST point still exists, so that is what is asserted.
  const tail = "Prefer an explicit discriminated union at the boundary.";
  const long = `${"A considered point about error handling that runs on and on. ".repeat(6)}${tail}`;
  expect(long.length).toBeGreaterThan(260);
  expect(long.indexOf(tail)).toBeGreaterThan(260);

  const lessons = learningSourceLessons(selectLearnableComments({ seen: [seen("named", long)] }, ["named"]));
  expect(lessons.length).toBeGreaterThan(1);
  expect(lessons).toContain(tail);
  for (const lesson of lessons) expect(lesson.length).toBeLessThanOrEqual(260);
});

test("the rendered source is an array of lesson strings and carries no provenance prose", async () => {
  // Every string in the file becomes a candidate lesson. A "Generated by keryx"
  // line in here is a line that ends up in somebody's SKILL.md.
  const { renderLearningSource } = await import("./review-learning");
  const parsed = JSON.parse(
    renderLearningSource(selectLearnableComments({ seen: [seen("named", "Check the empty case here.")] }, ["named"])),
  ) as unknown;
  expect(Array.isArray(parsed)).toBe(true);
  expect(parsed).toEqual(["Check the empty case here."]);
});

// --- the config --------------------------------------------------------------

test("an absent config is null, not a throw: a project that does not learn is not a project that is broken", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "keryx-learning-config-"));
  try {
    await mkdir(path.join(root, ".metaproject"), { recursive: true });
    expect(await loadReviewLearningConfig(root)).toBeNull();
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("a config naming a skill outside the <module>/<skill> shape is refused", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "keryx-learning-config-"));
  try {
    await mkdir(path.join(root, ".metaproject"), { recursive: true });
    await writeFile(
      path.join(root, ".metaproject", "review-learning.config.json"),
      JSON.stringify({ schemaVersion: 1, skill: "../../src/gdskills/bundled", repo: "o/r", authors: ["a"] }),
      "utf8",
    );
    await expect(loadReviewLearningConfig(root)).rejects.toThrow(/must be "<module>\/<skill>"/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

// --- AC7: learned content cannot reach the keryx repository ------------------

/**
 * This pins BEHAVIOUR THAT ALREADY EXISTS rather than adding a check.
 *
 * `applyLearningProposal` resolves the proposal's skill path and refuses anything
 * that is not inside `.metaproject/project-skills/`; that line predates this flow
 * and is the reason this flow needed no new guard. What did not exist was a test
 * naming `src/gdskills/bundled/` — the specific target whose corruption would
 * turn one project's local conventions into everybody's shipped template, since
 * the bundled tree is what `keryx update` copies into every installation.
 *
 * Without this, deleting the containment check leaves the suite green.
 */
test("AC7: apply refuses a proposal targeting src/gdskills/bundled, so a project cannot teach the shipped template", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "keryx-learn-containment-"));
  try {
    const bundled = path.join(root, "src", "gdskills", "bundled", "skills", "review", "code-learned-review");
    await mkdir(bundled, { recursive: true });
    await writeFile(path.join(bundled, "SKILL.md"), "# Shipped\n\nVersion: 1.0.0\n\n## Review Lessons\n\n", "utf8");
    await writeFile(path.join(bundled, "skill-changelog.md"), "# Changelog\n", "utf8");

    const proposalRoot = path.join(root, ".metaproject", "data", "gdskills", "proposals");
    await mkdir(proposalRoot, { recursive: true });
    const proposal: LearningProposal = {
      schemaVersion: 1,
      proposalId: "escape-attempt",
      sourceType: "review",
      sourcePath: ".metaproject/data/gdskills/learning-sources/o__r__7.json",
      skill: {
        module: "review",
        name: "code-learned-review",
        path: "src/gdskills/bundled/skills/review/code-learned-review",
        target: "src",
      },
      confidence: "high",
      lessons: ["One project's convention, aimed at everybody's shipped template."],
      suggestedSections: ["Review Lessons"],
      proposalPath: ".metaproject/data/gdskills/proposals/escape-attempt.json",
      createdAt: "2026-08-30T00:00:00.000Z",
      dryRun: false,
    };
    await writeFile(path.join(proposalRoot, "escape-attempt.json"), `${JSON.stringify(proposal, null, 2)}\n`, "utf8");

    await expect(applyLearningProposal(root, proposal.proposalPath)).rejects.toThrow(
      /must be under \.metaproject\/project-skills/,
    );

    // Refused, and refused BEFORE writing: the shipped file is untouched and the
    // version did not move.
    const { readFile } = await import("node:fs/promises");
    expect(await readFile(path.join(bundled, "SKILL.md"), "utf8")).toContain("Version: 1.0.0");
    expect(await readFile(path.join(bundled, "SKILL.md"), "utf8")).not.toContain("One project's convention");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("AC7: a path escaping project-skills with .. is refused on the same rule", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "keryx-learn-containment-"));
  try {
    const proposalRoot = path.join(root, ".metaproject", "data", "gdskills", "proposals");
    await mkdir(proposalRoot, { recursive: true });
    const proposal: LearningProposal = {
      schemaVersion: 1,
      proposalId: "dot-dot",
      sourceType: "review",
      sourcePath: "source.json",
      skill: {
        module: "alpha",
        name: "module",
        path: ".metaproject/project-skills/../../src/gdskills/bundled/rules/core",
        target: "src",
      },
      confidence: "high",
      lessons: ["A lesson pointed at the rules tree."],
      suggestedSections: ["Review Lessons"],
      proposalPath: ".metaproject/data/gdskills/proposals/dot-dot.json",
      createdAt: "2026-08-30T00:00:00.000Z",
      dryRun: false,
    };
    await writeFile(path.join(proposalRoot, "dot-dot.json"), `${JSON.stringify(proposal, null, 2)}\n`, "utf8");

    await expect(applyLearningProposal(root, proposal.proposalPath)).rejects.toThrow(
      /must be under \.metaproject\/project-skills/,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
