// Flow 361: the shape of the `AGENTS.override.md` keryx generates for a Codex
// entry with `mode: "override"` — a provenance line, the managed `keryx:index`
// block, then a copy of the team file Codex reads it instead of. Split out of
// `./entrypoint-writers` in flow 363 so the rules-export surface
// (`src/integrations/rules-export-target.ts`), which sits on the core entry's
// graph, can tell a keryx-generated override from a developer's own without
// importing the index block renderer (AFC-19, `src/core-package.test.ts`).
// `./entrypoint-writers` re-exports everything here.

import { createHash } from "node:crypto";
import { extractManagedRulesBlock, hasManagedRulesBlock, MANAGED_INDEX_BLOCK_END, stripManagedIndexBlock } from "./managed-index-block";
import { computeFencedRanges, indexOfMarkerLine } from "./marker-matching";

const OVERRIDE_PROVENANCE = /^<!-- keryx:override source="([^"\n]+)" sha256=([0-9a-f]{64}) /;

/**
 * `AGENTS.override.md`: a provenance line (source file and the sha256 of the
 * source content it was built from), the keryx block, then the source — with
 * any managed block the source itself still carries left out of the copy.
 * Codex reads the override INSTEAD of the source, so the copy is the point.
 *
 * Flow 363: `previous` is the override as it stands. A `keryx:rules` block in
 * it — written there by the rules-export surface, not by this function — is
 * carried into the new file right after the index block, so regenerating the
 * override (`update`, `rules sync`, `rules distill`) never drops it. It is
 * not carried when the copied source already has one: Codex would read two.
 * The recorded hash stays the hash of the source alone, so installing or
 * refreshing the rules block never makes the override look stale.
 */
export function renderCodexOverride(input: {
  source: string;
  sourceContent: string;
  block: string;
  sourcePath?: string;
  previous?: string;
}): string {
  const body = stripManagedIndexBlock(input.sourceContent, input.sourcePath ?? input.source);
  const provenance = `<!-- keryx:override source="${input.source}" sha256=${overrideSourceHash(input.sourceContent)} — generated by keryx; edit ${input.source}, then run \`keryx update\` -->`;
  const rules = input.previous === undefined || hasManagedRulesBlock(body) ? undefined : extractManagedRulesBlock(input.previous, "AGENTS.override.md");
  const carried = rules === undefined ? "" : `${rules.trimEnd()}\n\n`;
  return `${provenance}\n${input.block.trimEnd()}\n\n${carried}${body}`;
}

/**
 * `content` (a keryx-generated override with no `keryx:rules` block yet) with
 * `rulesBlock` placed where `renderCodexOverride` carries it — right after the
 * index block, ahead of the team text — so the first regeneration after an
 * install does not move it and rewrite the file. `undefined` when the
 * override has no index block to anchor on.
 */
export function insertRulesBlockAfterIndex(content: string, rulesBlock: string): string | undefined {
  const end = indexOfMarkerLine(content, MANAGED_INDEX_BLOCK_END, computeFencedRanges(content));
  if (end < 0) return undefined;
  const newline = content.indexOf("\n", end);
  const head = newline < 0 ? `${content}\n` : content.slice(0, newline + 1);
  const tail = newline < 0 ? "" : content.slice(newline + 1).replace(/^\r?\n/, "");
  return `${head}\n${rulesBlock.trimEnd()}\n\n${tail}`;
}

export function parseCodexOverrideProvenance(content: string): { source: string; sha256: string } | undefined {
  const match = OVERRIDE_PROVENANCE.exec(content);
  return match?.[1] !== undefined && match[2] !== undefined ? { source: match[1], sha256: match[2] } : undefined;
}

/** The hash a provenance line records: the source content's sha256, nothing else. */
export function overrideSourceHash(sourceContent: string): string {
  return createHash("sha256").update(sourceContent, "utf8").digest("hex");
}
