// Flow 361: the shape of the `AGENTS.override.md` keryx generates for a Codex
// entry with `mode: "override"` — a provenance line, the managed `keryx:index`
// block, then a copy of the team file Codex reads it instead of. Split out of
// `./entrypoint-writers` in flow 363 so the rules-export surface
// (`src/integrations/rules-export-target.ts`), which sits on the core entry's
// graph, can tell a keryx-generated override from a developer's own without
// importing the index block renderer (AFC-19, `src/core-package.test.ts`).
// `./entrypoint-writers` re-exports everything here.

import { createHash } from "node:crypto";
import { RULES_BLOCK_START_MARKER } from "./export-render";
import { extractManagedRulesBlock, hasManagedRulesBlock, MANAGED_INDEX_BLOCK_END, stripManagedIndexBlock } from "./managed-index-block";
import { computeFencedRanges, indexOfMarkerLine } from "./marker-matching";

const OVERRIDE_PROVENANCE = /^<!-- keryx:override source="([^"\n]+)" sha256=([0-9a-f]{64}) /;

/**
 * `AGENTS.override.md`: a provenance line (source file and the sha256 of the
 * source content it was built from), the keryx block, then the source — with
 * any managed block the source itself still carries left out of the copy.
 * Codex reads the override INSTEAD of the source, so the copy is the point.
 *
 * Flow 363: `previous` is the override as it stands. The `keryx:rules` block
 * in its own slot (`overrideRulesSlot`) — written there by the rules-export
 * surface, not by this function — is carried into the new file at the same
 * place, so regenerating the override (`update`, `rules sync`, `rules
 * distill`) never drops it. A block inside the previous copy of the team file
 * is the team's text, never carried (review round 1, F-003): a block the team
 * removed from `AGENTS.md` would otherwise come back on every regeneration.
 * Nothing is carried when the copied source has one of its own: Codex would
 * read two. The recorded hash stays the hash of the source alone, so
 * installing or refreshing the rules block never makes the override look stale.
 */
export function renderCodexOverride(input: {
  source: string;
  sourceContent: string;
  block: string;
  sourcePath?: string;
  previous?: string;
}): string {
  const body = stripManagedIndexBlock(input.sourceContent, input.sourcePath ?? input.source);
  const provenance = `<!-- keryx:override source="${input.source}" sha256=${overrideSourceHash(input.sourceContent)} — generated by keryx; edit ${input.source}, then run \`keryx update\` -->`;
  const rules = input.previous === undefined || hasManagedRulesBlock(body) ? undefined : overrideRulesSlot(input.previous)?.block;
  const carried = rules === undefined ? "" : `${rules.trimEnd()}\n\n`;
  return `${provenance}\n${input.block.trimEnd()}\n\n${carried}${body}`;
}

/** Where keryx's own `keryx:rules` block sits in an override: offsets into the content, and the block itself. */
export type OverrideRulesSlot = {
  /** Offset of the block's start marker line. */
  readonly start: number;
  /** Offset just past the block's end marker line and the blank lines after it, where the copied team text begins. */
  readonly end: number;
  /** The block, marker lines included, without a trailing line terminator. */
  readonly block: string;
};

/**
 * The `keryx:rules` block in an override's own slot: the first thing after
 * the index block's end marker, blank lines aside, and so ahead of the copied
 * team text. `undefined` when the override has no index block, or the slot is
 * empty — a block further down is part of the copy of the team file, which
 * keryx never edits. Throws `UnterminatedMetaprojectReferenceError` for a slot
 * block with no end marker.
 */
export function overrideRulesSlot(content: string): OverrideRulesSlot | undefined {
  const indexEnd = indexOfMarkerLine(content, MANAGED_INDEX_BLOCK_END, computeFencedRanges(content));
  if (indexEnd < 0) return undefined;
  let start = endOfLine(content, indexEnd);
  while (start < content.length && isBlankLine(content, start)) start = endOfLine(content, start);
  if (lineAt(content, start) !== RULES_BLOCK_START_MARKER) return undefined;
  const block = extractManagedRulesBlock(content.slice(start), "AGENTS.override.md");
  if (block === undefined) return undefined;
  let end = endOfLine(content, start + block.length);
  while (end < content.length && isBlankLine(content, end)) end = endOfLine(content, end);
  return { start, end, block };
}

/**
 * `content` with keryx's slot holding `rulesBlock`: the slot's block replaced,
 * or — when the slot is empty — the block placed right after the index block,
 * ahead of the team text, where `renderCodexOverride` carries it, so the next
 * regeneration does not move it and rewrite the file. The copied team text is
 * never touched. `undefined` when the override has no index block to anchor on.
 */
export function withOverrideRulesSlot(content: string, rulesBlock: string): string | undefined {
  const slot = overrideRulesSlot(content);
  if (slot !== undefined) return `${content.slice(0, slot.start)}${rulesBlock.trimEnd()}\n\n${content.slice(slot.end)}`;
  const end = indexOfMarkerLine(content, MANAGED_INDEX_BLOCK_END, computeFencedRanges(content));
  if (end < 0) return undefined;
  const newline = content.indexOf("\n", end);
  const head = newline < 0 ? `${content}\n` : content.slice(0, newline + 1);
  const tail = newline < 0 ? "" : content.slice(newline + 1).replace(/^\r?\n/, "");
  return `${head}\n${rulesBlock.trimEnd()}\n\n${tail}`;
}

/**
 * `content` without the block in keryx's slot, in the shape
 * `renderCodexOverride` gives an override with no rules block — so removing
 * what an install added gives back the file as it was. `content` itself when
 * the slot is empty.
 */
export function withoutOverrideRulesSlot(content: string): string {
  const slot = overrideRulesSlot(content);
  return slot === undefined ? content : `${content.slice(0, slot.start)}${content.slice(slot.end)}`;
}

function endOfLine(content: string, lineStart: number): number {
  const newline = content.indexOf("\n", lineStart);
  return newline < 0 ? content.length : newline + 1;
}

function lineAt(content: string, lineStart: number): string {
  return content.slice(lineStart, endOfLine(content, lineStart)).replace(/\r?\n$/, "");
}

function isBlankLine(content: string, lineStart: number): boolean {
  return lineAt(content, lineStart).trim() === "";
}

export function parseCodexOverrideProvenance(content: string): { source: string; sha256: string } | undefined {
  const match = OVERRIDE_PROVENANCE.exec(content);
  return match?.[1] !== undefined && match[2] !== undefined ? { source: match[1], sha256: match[2] } : undefined;
}

/** The hash a provenance line records: the source content's sha256, nothing else. */
export function overrideSourceHash(sourceContent: string): string {
  return createHash("sha256").update(sourceContent, "utf8").digest("hex");
}
