import { appendFile, mkdir, readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { WorkspaceService, localWorkspaceAuthorizationServer } from "./workspace-service";
import type { SacAuthorizationServer } from "./index";
import type { StrictSacGuard } from "./index";

export type CollaborationActivity = Readonly<{ schemaVersion: "1.0"; id: string; kind: "reference-added" | "handoff-recorded"; workspaceId: string; actorSubject: string; occurredAt: string; reference?: { kind: "worktree" | "session"; uri: string; revision?: string }; handoff?: { from: string; to: string; artifactRef: string } }>;
export class CollaborationServiceError extends Error { constructor(readonly code: "access_denied" | "invalid_activity", message: string) { super(message); } }
export class CollaborationService {
  constructor(private readonly input: { workspaceRoot: string; workspaces: WorkspaceService; authorizationServer: SacAuthorizationServer; now?: () => Date }) {}
  private file(id: string) { return path.join(this.input.workspaceRoot, ".metaproject", "workspaces", id, "activity.jsonl"); }
  async overview(input: { request: unknown; requestCorrelationId: string; workspaceId: string }) { const manifest = await this.input.workspaces.show(input); return normalizeCollaborationResult({ workspaceId: manifest.id, references: manifest.resources.filter((r) => r.kind === "worktree" || r.kind === "session"), activity: await this.activity(input) }); }
  async activity(input: { request: unknown; requestCorrelationId: string; workspaceId: string }): Promise<CollaborationActivity[]> { await this.input.workspaces.show(input); try { return (await readFile(this.file(input.workspaceId), "utf8")).trim().split("\n").filter(Boolean).map((line) => this.validate(JSON.parse(line))); } catch (error) { if (typeof error === "object" && error && "code" in error && error.code === "ENOENT") return []; throw error; } }
  async record(input: { request: unknown; requestCorrelationId: string; workspaceId: string; activity: Omit<CollaborationActivity, "schemaVersion" | "id" | "workspaceId" | "actorSubject" | "occurredAt"> }) { const actor = await this.input.authorizationServer.actorContextFor(input.request, input.requestCorrelationId); if (!actor) throw new CollaborationServiceError("access_denied", "trusted ActorContext is required"); return this.input.workspaces.withAuthorizedActor({ actorContext: actor, workspaceId: input.workspaceId, action: "write", execute: async (manifest) => { if (manifest.members.find((m) => m.subject === actor.subject)?.role !== "owner") throw new CollaborationServiceError("access_denied", "owner authority is required"); const activity = this.validate({ schemaVersion: "1.0", id: `activity-${randomUUID()}`, workspaceId: manifest.id, actorSubject: actor.subject, occurredAt: (this.input.now ?? (() => new Date()))().toISOString(), ...input.activity }); await mkdir(path.dirname(this.file(manifest.id)), { recursive: true, mode: 0o700 }); await appendFile(this.file(manifest.id), `${JSON.stringify(activity)}\n`, { mode: 0o600 }); return normalizeCollaborationResult(activity); } }); }
  private validate(value: unknown): CollaborationActivity { if (!value || typeof value !== "object" || Array.isArray(value)) throw new CollaborationServiceError("invalid_activity", "activity must be an object"); const r = value as Record<string, unknown>; const allowed = new Set(["schemaVersion", "id", "kind", "workspaceId", "actorSubject", "occurredAt", "reference", "handoff"]); if (Object.keys(r).some((key) => !allowed.has(key) || /prompt|transcript|secret|reasoning|content/i.test(key))) throw new CollaborationServiceError("invalid_activity", "activity contains forbidden metadata"); if (r.schemaVersion !== "1.0" || (r.kind !== "reference-added" && r.kind !== "handoff-recorded") || typeof r.id !== "string" || typeof r.workspaceId !== "string" || typeof r.actorSubject !== "string" || typeof r.occurredAt !== "string") throw new CollaborationServiceError("invalid_activity", "activity is malformed"); return r as unknown as CollaborationActivity; }
}
export function createLocalCollaborationService(cwd: string) { const guard: StrictSacGuard = { mode: "strict", availability: "available", decision: "pass", policyRevision: "local-offline-v1" }; const authorizationServer = localWorkspaceAuthorizationServer(); return new CollaborationService({ workspaceRoot: cwd, authorizationServer, workspaces: new WorkspaceService({ workspaceRoot: cwd, authorizationServer, strictGuard: guard }) }); }
export function normalizeCollaborationResult<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T; }
