// Flow 367, AC5-AC9: enrich and collect keep a page's changelog, attestation
// entries, Version and front matter. The fixture is shaped like a real enriched
// page from the 2026-10-01 incident (acme-frontend `components/src-auth.md`):
// still `Status: draft`, the collect marker inside its changelog, a tool-written
// attestation entry on top.

import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import type { NormalizedEvent, ProviderPort, StreamOptions } from "../harness/provider/types";
import { type ProviderFactory, wikiEnrich } from "./enrich";
import { wrapReferenceSection } from "./managed-block";
import {
  checkPageInvariants,
  compareVersions,
  generatedSectionHeadings,
  mergeGeneratedSections,
  nextPageVersion,
  pageVersion,
  parseChangelog,
  preserveEnrichInvariants,
  unwrapFencedReply,
} from "./page-invariants";
import { createWikiWriteContext, restoreWikiPage, writeWikiPage } from "./history";
import { wikiCollect, wikiValidate } from "./service";

const ATTESTATION =
  "- 0.2.0 - Deterministic repair by `.metaproject/core/gdwiki/verify-prose.mjs` (1 hedge-removed): a wrong-attribution path was replaced. Status unchanged -- the gate re-decides on this text.";
const GENERATED_ENTRY =
  "- 0.1.0 - Generated by `keryx wiki collect` at 2026-09-23T07:33:13.595Z. Prose sections are drafts for the gdwiki enrich workflow.";

const ENRICHED_PAGE = `---
Title: Module src/alpha
Version: 0.2.0
Type: component
Status: draft
Summary: "\`src/alpha\` groups 2 file(s)."
VerifiedAt: 1234567
---
# Module src/alpha

## Purpose

Hand-written prose about alpha that must survive every collect.

## Reference (from code graph)

Extracted deterministically by \`keryx wiki collect\`; regenerated by
\`--force\`. The prose sections above are the agent/human-owned part.

### Key files

- \`src/alpha/old.ts\` - stale entry from an older graph

## Related Wiki

- [Wiki Index](../index.md)

## Changelog

${ATTESTATION}

${GENERATED_ENTRY}
`;

const MODEL_PROSE = `# Module src/alpha

## Purpose

Rewritten prose with plenty of words so that structural validation passes cleanly.

## Reference (from code graph)

The model also scribbled over the reference.
`;

function stubProvider(reply: string): ProviderPort {
  return {
    describe() {
      return {
        capabilities: {
          streaming: true,
          toolCalls: false,
          parallelToolCalls: false,
          structuredOutput: false,
          reasoningMetadata: false,
          promptCaching: false,
          vision: false,
          tokenCounting: false,
          modelListing: false,
        },
        descriptor: { providerId: "stub" },
      };
    },
    async *stream(_request, opts: StreamOptions): AsyncIterable<NormalizedEvent> {
      yield { kind: "text_delta", sequence: 0, attemptId: opts.attemptId, text: reply };
      yield { kind: "model_end", sequence: 1, attemptId: opts.attemptId };
    },
  };
}

let root: string;

beforeEach(async () => {
  root = await mkdtemp(path.join(tmpdir(), "keryx-page-invariants-"));
  const graphDir = path.join(root, ".metaproject", "data", "gdgraph", "storage");
  await mkdir(graphDir, { recursive: true });
  const nodes = ["a", "b"].map((f) => ({ id: `src/alpha/${f}.ts`, kind: "file", path: `src/alpha/${f}.ts` }));
  await writeFile(path.join(graphDir, "nodes.jsonl"), nodes.map((n) => JSON.stringify(n)).join("\n"), "utf8");
  await writeFile(path.join(graphDir, "edges.jsonl"), "", "utf8");
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

const alphaPath = (): string => path.join(root, ".metaproject", "wiki", "components", "src-alpha.md");

async function seedAlpha(content: string): Promise<void> {
  await mkdir(path.dirname(alphaPath()), { recursive: true });
  await writeFile(alphaPath(), content, "utf8");
}

async function enrichWith(reply: string): Promise<Awaited<ReturnType<typeof wikiEnrich>>> {
  const factory: ProviderFactory = () => stubProvider(reply);
  return wikiEnrich({ cwd: root, page: "components/src-alpha.md", providerFactory: factory, onPage: () => {} });
}

describe("parsing", () => {
  test("changelog entries keep their exact text and version", () => {
    expect(parseChangelog(ENRICHED_PAGE)).toEqual([
      { text: ATTESTATION, version: "0.2.0" },
      { text: GENERATED_ENTRY, version: "0.1.0" },
    ]);
    expect(parseChangelog("# No changelog\n")).toBeNull();
  });

  test("Version from YAML and from legacy metadata lines", () => {
    expect(pageVersion(ENRICHED_PAGE)).toBe("0.2.0");
    expect(pageVersion("# Module x\n\nVersion: 0.1.0\nType: component\n\n## Summary\n")).toBe("0.1.0");
  });

  test("the next version is one patch above whichever of Version and changelog is newer", () => {
    expect(nextPageVersion(ENRICHED_PAGE)).toBe("0.2.1");
    const behind = ENRICHED_PAGE.replace("Version: 0.2.0", "Version: 0.1.0");
    expect(nextPageVersion(behind)).toBe("0.2.1");
    expect(compareVersions("0.10.0", "0.9.9")).toBeGreaterThan(0);
  });

  test("generated sections of a module page are Reference and Related Wiki, never prose placeholders", async () => {
    await wikiCollect({ cwd: root });
    const generated = await readFile(alphaPath(), "utf8");
    expect(generatedSectionHeadings(generated)).toEqual(["Reference (from code graph)", "Related Wiki"]);
  });
});

describe("checkPageInvariants", () => {
  test("reports each kind of breakage", () => {
    const kinds = (after: string): string[] => checkPageInvariants(ENRICHED_PAGE, after).map((v) => v.kind);
    expect(kinds(ENRICHED_PAGE)).toEqual([]);
    expect(kinds(ENRICHED_PAGE.replace(/## Changelog[\s\S]*$/, ""))).toEqual(["changelog-dropped"]);
    expect(kinds(ENRICHED_PAGE.replace("1 hedge-removed", "one hedge removed"))).toEqual(["changelog-entry-altered"]);
    expect(kinds(ENRICHED_PAGE.replace("Version: 0.2.0", "Version: 0.1.0"))).toEqual(["version-behind-changelog"]);
    expect(kinds(ENRICHED_PAGE.replace("VerifiedAt: 1234567\n", ""))).toEqual(["frontmatter-key-dropped"]);
    const wrapped = wrapReferenceSection(ENRICHED_PAGE)!;
    expect(checkPageInvariants(wrapped, ENRICHED_PAGE).map((v) => v.kind)).toEqual(["managed-block-dropped"]);
    expect(kinds(ENRICHED_PAGE.replace("## Related Wiki", "## Reference\n\n- dup\n\n## Related Wiki"))).toEqual(["section-duplicated"]);
  });
});

describe("preserveEnrichInvariants", () => {
  test("front matter, changelog and Version come back from the original; one entry is added", () => {
    const modelOutput = `---\nTitle: Something else\nVersion: 0.0.1\nStatus: accepted\n---\n${MODEL_PROSE}\n## Changelog\n\n- 9.9.9 - The model made this up.\n`;
    const result = preserveEnrichInvariants(ENRICHED_PAGE, modelOutput, "Prose rewritten by `keryx wiki enrich`.");

    expect(result).toContain("Rewritten prose");
    expect(result).toContain("VerifiedAt: 1234567");
    expect(result).toContain("Status: draft");
    expect(result).not.toContain("The model made this up");
    expect(parseChangelog(result)!.map((entry) => entry.text)).toEqual([
      "- 0.2.1 - Prose rewritten by `keryx wiki enrich`.",
      ATTESTATION,
      GENERATED_ENTRY,
    ]);
    expect(pageVersion(result)).toBe("0.2.1");
    expect(checkPageInvariants(ENRICHED_PAGE, result)).toEqual([]);
  });
});

describe("mergeGeneratedSections", () => {
  test("replaces Reference and Related Wiki only; prose, front matter and changelog stay byte-identical", async () => {
    await wikiCollect({ cwd: root });
    const generated = await readFile(alphaPath(), "utf8");

    const merged = mergeGeneratedSections(ENRICHED_PAGE, generated, "Generated sections regenerated.");

    expect(merged).toContain("Hand-written prose about alpha that must survive every collect.");
    expect(merged).not.toContain("stale entry from an older graph");
    expect(merged).toContain("`src/alpha/a.ts`");
    expect(merged.startsWith(ENRICHED_PAGE.slice(0, ENRICHED_PAGE.indexOf("Version:")))).toBe(true);
    expect(merged).toContain('Summary: "`src/alpha` groups 2 file(s)."');
    expect(parseChangelog(merged)!.map((entry) => entry.text)).toEqual([
      "- 0.2.1 - Generated sections regenerated.",
      ATTESTATION,
      GENERATED_ENTRY,
    ]);
    expect(checkPageInvariants(ENRICHED_PAGE, merged)).toEqual([]);
  });

  test("a Reference heading an enricher shortened is replaced, never duplicated", async () => {
    await wikiCollect({ cwd: root });
    const generated = await readFile(alphaPath(), "utf8");
    const shortened = ENRICHED_PAGE.replace("## Reference (from code graph)", "## Reference");
    const merged = mergeGeneratedSections(shortened, generated, "regenerated");
    expect(merged.match(/^## Reference\b/gm)).toHaveLength(1);
    expect(merged).not.toContain("stale entry from an older graph");
  });

  test("nothing to regenerate means the page comes back unchanged, with no new entry", async () => {
    await wikiCollect({ cwd: root });
    const generated = await readFile(alphaPath(), "utf8");
    const once = mergeGeneratedSections(ENRICHED_PAGE, generated, "regenerated");
    expect(mergeGeneratedSections(once, generated, "regenerated")).toBe(once);
  });

  test("map pages: an enriched page keeps prose written under a generated heading; an untouched one is regenerated", () => {
    // Shaped like acme's enriched quality-map: the enricher reorganised the
    // page and wrote an interpretation under the generator's own heading.
    const generated = [
      "# Quality Map", "", "Version: 0.1.0", "Type: architecture", "Status: draft", "",
      "## Summary", "", "Health score 94.", "",
      "## Findings By Source", "", "- complexity: 479", "",
      "## Related Wiki", "", "- [Wiki Index](../index.md)", "",
      "## Changelog", "", "- 0.1.0 - Generated by `keryx wiki collect` at 2026-10-01T00:00:00.000Z.", "",
    ].join("\n");
    const enrichedMap = [
      "# Quality Map", "", "Version: 0.1.0", "Type: architecture", "Status: draft", "",
      "## Overview", "", "What this page is for, in prose.", "",
      "## Findings by Source", "", "No findings were reported in this run.", "",
      "### Interpretation", "", "The absence of findings is limited in scope.", "",
      "## Related Wiki", "", "- [Wiki Index](../index.md)", "",
      "## Changelog", "", "- 0.1.0 - Generated by `keryx wiki collect` at 2026-09-01T00:00:00.000Z.", "",
    ].join("\n");
    const merged = mergeGeneratedSections(enrichedMap, generated, "regenerated");
    expect(merged).toBe(enrichedMap);

    const untouchedMap = generated
      .replace("- complexity: 479", "- complexity: 12")
      .replace("2026-10-01T00:00:00.000Z", "2026-09-01T00:00:00.000Z");
    const refreshed = mergeGeneratedSections(untouchedMap, generated, "regenerated");
    expect(refreshed).toContain("- complexity: 479");
    expect(refreshed).not.toContain("- complexity: 12");
    expect(pageVersion(refreshed)).toBe("0.1.1");
  });

  test("Related Wiki: an enricher's own lines survive; module links and reworded boilerplate do not", () => {
    const generated = [
      "# Module x", "", "Version: 0.1.0", "Status: draft", "",
      "## Related Wiki", "", "Graph-derived - regenerated by `keryx wiki collect --force`. Only pages that",
      "exist are linked.", "", "- [Wiki Index](../index.md)", "- [Module src/new](src-new.md)", "",
      "## Changelog", "", "- 0.1.0 - Generated by `keryx wiki collect` at 2026-10-01T00:00:00.000Z.", "",
    ].join("\n");
    const existing = [
      "# Module x", "", "Version: 0.1.0", "Status: draft", "",
      "## Purpose", "", "Prose.", "",
      "## Related Wiki", "", "Graph-derived. Only pages that exist are linked.", "",
      "- [Wiki Index](../index.md)", "- [Module src/removed](src-removed.md)", "- [Testing guide](../guides/testing.md)", "",
      "Use the wiki index to find related testing pages.", "",
      "## Changelog", "", "- 0.1.0 - Generated by `keryx wiki collect` at 2026-09-01T00:00:00.000Z.", "",
    ].join("\n");
    const merged = mergeGeneratedSections(existing, generated, "regenerated");
    expect(merged).toContain("- [Module src/new](src-new.md)");
    expect(merged).not.toContain("src-removed.md");
    expect(merged).toContain("- [Testing guide](../guides/testing.md)");
    expect(merged).toContain("Use the wiki index to find related testing pages.");
    expect(merged).not.toContain("Graph-derived. Only pages that exist are linked.");
    expect(mergeGeneratedSections(merged, generated, "regenerated")).toBe(merged);
  });

  test("a managed Reference block edited by hand is left alone", async () => {
    await wikiCollect({ cwd: root });
    const generated = await readFile(alphaPath(), "utf8");
    const wrapped = wrapReferenceSection(ENRICHED_PAGE)!.replace("stale entry", "a human's correction");
    const merged = mergeGeneratedSections(wrapped, generated, "regenerated");
    expect(merged).toContain("a human's correction");
  });
});

describe("enrich (AC5-AC7, AC9)", () => {
  test("AC5: a reply without ## Changelog leaves every prior entry on disk", async () => {
    await seedAlpha(ENRICHED_PAGE);
    const reply = `---\nTitle: Module src/alpha\nVersion: 0.2.0\nStatus: draft\n---\n${MODEL_PROSE}`;
    const result = await enrichWith(reply);

    expect(result.pages.map((page) => page.action)).toEqual(["enriched"]);
    const onDisk = await readFile(alphaPath(), "utf8");
    expect(onDisk).toContain("Rewritten prose");
    const texts = parseChangelog(onDisk)!.map((entry) => entry.text);
    expect(texts).toContain(ATTESTATION);
    expect(texts).toContain(GENERATED_ENTRY);
  });

  test("AC6: a reply that rewords the attestation entry leaves the original bytes on disk", async () => {
    await seedAlpha(ENRICHED_PAGE);
    const reworded = ATTESTATION.replace("Deterministic repair by", "Repaired, as the model would put it, by");
    const reply = `---\nTitle: Module src/alpha\nVersion: 0.2.0\nStatus: draft\n---\n${MODEL_PROSE}\n## Changelog\n\n${reworded}\n\n${GENERATED_ENTRY}\n`;
    await enrichWith(reply);

    const onDisk = await readFile(alphaPath(), "utf8");
    expect(onDisk).toContain(ATTESTATION);
    expect(onDisk).not.toContain("as the model would put it");
  });

  test("AC7: a reply that lowers Version is written with Version at or above the newest changelog entry", async () => {
    await seedAlpha(ENRICHED_PAGE);
    const reply = `---\nTitle: Module src/alpha\nVersion: 0.0.1\nStatus: draft\n---\n${MODEL_PROSE}`;
    await enrichWith(reply);

    const onDisk = await readFile(alphaPath(), "utf8");
    const newest = parseChangelog(onDisk)!.map((entry) => entry.version!).sort(compareVersions).at(-1)!;
    expect(compareVersions(pageVersion(onDisk), newest)).toBeGreaterThanOrEqual(0);
    expect(pageVersion(onDisk)).toBe("0.2.1");
  });

  test("a reply wrapped in a ```markdown fence is unwrapped, not written as one big code block", async () => {
    await seedAlpha(ENRICHED_PAGE);
    const inner = `---\nTitle: Module src/alpha\nVersion: 0.2.0\nStatus: draft\n---\n${MODEL_PROSE}\n\`\`\`\nHost process\n└── child\n\`\`\`\n`;
    const result = await enrichWith(`\`\`\`markdown\n${inner}\`\`\`\n`);

    expect(result.pages.map((page) => page.action)).toEqual(["enriched"]);
    const onDisk = await readFile(alphaPath(), "utf8");
    expect(onDisk).not.toContain("```markdown");
    expect(onDisk.match(/^---$/gm)).toHaveLength(2); // one front matter, not two
    expect(onDisk).toContain("Host process"); // inner code block kept
    expect(parseChangelog(onDisk)!.map((entry) => entry.text)).toContain(ATTESTATION);
    expect(unwrapFencedReply("plain page\n\n```\ncode\n```\n")).toBe("plain page\n\n```\ncode\n```\n");
  });

  test("AC9: a reply that drops the managed Reference block is refused, the page untouched, the run failed", async () => {
    const wrapped = wrapReferenceSection(ENRICHED_PAGE)!;
    await seedAlpha(wrapped);
    const reply = `---\nTitle: Module src/alpha\nVersion: 0.2.0\nStatus: draft\n---\n${MODEL_PROSE}`;
    const result = await enrichWith(reply);

    expect(result.failed).toBe(1);
    expect(result.pages[0]!.reason).toContain("invariant:");
    expect(result.pages[0]!.reason).toContain("managed-block-dropped");
    expect(await readFile(alphaPath(), "utf8")).toBe(wrapped);
  });
});

describe("review round 1 fixes", () => {
  const PAGE = [
    "---", "Title: X", "Version: 0.2.0", "Status: draft", "---", "# X", "",
    "## Purpose", "", "Prose.", "",
    "## Related Wiki", "", "- [Wiki Index](../index.md)", "",
    "## Changelog", "", "- 0.2.0 - Second.", "", "- 0.1.0 - First.", "",
  ].join("\n");
  const GENERATED = [
    "# X", "", "Version: 0.1.0", "Status: draft", "",
    "## Related Wiki", "", "- [Wiki Index](../index.md)", "- [Module src/new](src-new.md)", "",
    "## Changelog", "", "- 0.1.0 - Generated by `keryx wiki collect` at 2026-10-01T00:00:00.000Z.", "",
  ].join("\n");

  test("L-004: a ## Changelog inside a code fence is example text, not the changelog", () => {
    const fenced = PAGE.replace("## Purpose\n\nProse.\n", "## Purpose\n\n```markdown\n## Changelog\n\n- 9.9.9 - example\n```\n");
    expect(parseChangelog(fenced)!.map((entry) => entry.version)).toEqual(["0.2.0", "0.1.0"]);
    const enriched = preserveEnrichInvariants(fenced, fenced.replace("- 0.2.0 - Second.\n\n", ""), "note");
    // The real changelog was restored and got the entry; the fenced example is untouched.
    expect(enriched).toContain("```markdown\n## Changelog\n\n- 9.9.9 - example\n```");
    expect(parseChangelog(enriched)!.map((entry) => entry.text)).toEqual(["- 0.2.1 - note", "- 0.2.0 - Second.", "- 0.1.0 - First."]);
    // A writer that drops the real changelog but keeps the fenced one is caught.
    const dropped = fenced.replace(/\n## Changelog\n\n- 0\.2\.0[\s\S]*$/, "\n");
    expect(checkPageInvariants(fenced, dropped).map((v) => v.kind)).toEqual(["changelog-dropped"]);
  });

  test("L-005 / T-003: a CRLF page keeps CRLF, and a second merge is a no-op", () => {
    const crlf = PAGE.replace(/\n/g, "\r\n");
    const merged = mergeGeneratedSections(crlf, GENERATED, "regenerated");
    expect(merged).not.toBe(crlf);
    expect(merged.replace(/\r\n/g, "")).not.toContain("\n"); // no bare LF anywhere
    expect(merged).toContain("- [Module src/new](src-new.md)\r\n");
    expect(mergeGeneratedSections(merged, GENERATED, "regenerated")).toBe(merged);

    const enriched = preserveEnrichInvariants(crlf, "---\nTitle: X\nStatus: draft\n---\n# X\n\nNew prose.\n", "note");
    expect(enriched.replace(/\r\n/g, "")).not.toContain("\n");
    expect(checkPageInvariants(crlf, enriched)).toEqual([]);
  });

  test("L-006: a hand-written '## Reference implementation notes' is prose, not the generated Reference", () => {
    const notes = PAGE.replace("## Related Wiki", "## Reference implementation notes\n\nKeep me.\n\n## Related Wiki");
    const generated = GENERATED.replace("## Related Wiki", "## Reference (from code graph)\n\n- generated list\n\n## Related Wiki");
    const merged = mergeGeneratedSections(notes, generated, "regenerated");
    expect(merged).toContain("## Reference implementation notes\n\nKeep me.");
    expect(merged).toContain("## Reference (from code graph)\n\n- generated list");
  });

  test("L-007: the new entry goes above the first entry, never onto an intro line or the next heading", () => {
    const intro = PAGE.replace("## Changelog\n\n", "## Changelog\n\nEntries newest first.\n\n");
    const withIntro = preserveEnrichInvariants(intro, intro, "note");
    expect(withIntro).toContain("Entries newest first.\n\n- 0.2.1 - note\n\n- 0.2.0 - Second.");

    const empty = `${PAGE.replace(/## Changelog[\s\S]*$/, "## Changelog\n\n## Notes\n\nAfter.\n")}`;
    const intoEmpty = preserveEnrichInvariants(empty, empty, "note");
    expect(intoEmpty).toContain("## Changelog\n\n- 0.2.1 - note\n\n## Notes");

    const single = PAGE.replace("- 0.2.0 - Second.\n\n", "");
    expect(preserveEnrichInvariants(single, single, "note")).toContain("## Changelog\n\n- 0.2.1 - note\n- 0.1.0 - First.");
  });

  test("L-008: x.y and pre-release versions bump in place; a lower-case quoted key keeps its spelling", () => {
    const short = PAGE.replace("Version: 0.2.0", "Version: 1.0").replace(/## Changelog[\s\S]*$/, "## Changelog\n");
    expect(pageVersion(preserveEnrichInvariants(short, short, "note"))).toBe("1.0.1");
    const beta = short.replace("Version: 1.0", "Version: 2.0.0-beta");
    expect(pageVersion(preserveEnrichInvariants(beta, beta, "note"))).toBe("2.0.1");
    const lower = short.replace("Version: 1.0", 'version: "1.0.0"');
    expect(preserveEnrichInvariants(lower, lower, "note")).toContain('version: "1.0.1"');
  });
});

describe("wiki validate (AC10)", () => {
  const issuesFor = async (kind: string): Promise<string[]> =>
    (await wikiValidate(root)).issues
      .filter((issue) => issue.page.endsWith("components/src-alpha.md") && issue.kind === kind)
      .map((issue) => issue.message);

  test("Version below the newest changelog entry is an error, with or without history", async () => {
    await seedAlpha(ENRICHED_PAGE.replace("Version: 0.2.0", "Version: 0.1.0"));
    expect(await issuesFor("version")).toEqual(["Version 0.1.0 is lower than the newest changelog entry 0.2.0"]);
  });

  test("a changelog the previous version had, and the page no longer has, is an error", async () => {
    await seedAlpha(ENRICHED_PAGE);
    // The damage arrives through a keryx write with no guard — what an older
    // keryx enrich did on 2026-10-01 — so the history records it.
    await writeWikiPage(createWikiWriteContext(root, "wiki enrich (old)"), alphaPath(), ENRICHED_PAGE.replace(/\n## Changelog[\s\S]*$/, "\n"));

    const messages = await issuesFor("changelog");
    expect(messages.some((message) => message.includes("had a ## Changelog section"))).toBe(true);
  });

  test("a reworded attestation entry is an error", async () => {
    await seedAlpha(ENRICHED_PAGE);
    await writeWikiPage(createWikiWriteContext(root, "wiki enrich (old)"), alphaPath(), ENRICHED_PAGE.replace("Deterministic repair by", "Repaired by"));

    const messages = await issuesFor("changelog");
    expect(messages.some((message) => message.includes("changelog entry removed or reworded: - 0.2.0"))).toBe(true);
  });

  test("L-001: a hand edit (not in the history) is not judged — it may be deliberate and nothing could clear it", async () => {
    await seedAlpha(ENRICHED_PAGE);
    await writeWikiPage(createWikiWriteContext(root, "test"), alphaPath(), ENRICHED_PAGE.replace("Hand-written prose", "Edited prose"));
    await writeFile(alphaPath(), ENRICHED_PAGE.replace("Deterministic repair by", "Repaired by"), "utf8");
    expect(await issuesFor("changelog")).toEqual([]);
  });

  test("L-010: an unreadable page history is reported, not read as 'no history'", async () => {
    await seedAlpha(ENRICHED_PAGE);
    await writeWikiPage(createWikiWriteContext(root, "test"), alphaPath(), ENRICHED_PAGE.replace("Hand-written prose", "Edited prose"));
    await writeFile(path.join(root, ".metaproject", "data", "gdwiki", "history", "components", "src-alpha", "index.md"), "garbage\n", "utf8");
    expect((await issuesFor("metadata")).some((message) => message.startsWith("page history unreadable"))).toBe(true);
  });

  test("after restoring a damaged page, validate is clean (judged against the pre-damage history)", async () => {
    await seedAlpha(ENRICHED_PAGE);
    await wikiCollect({ cwd: root, force: true });
    const collected = await readFile(alphaPath(), "utf8");
    await writeWikiPage(createWikiWriteContext(root, "wiki enrich (old)"), alphaPath(), collected.replace("Deterministic repair by", "Repaired by"));
    expect((await issuesFor("changelog")).length).toBe(1);

    await restoreWikiPage(createWikiWriteContext(root, "wiki restore"), "components/src-alpha.md");
    expect(await issuesFor("changelog")).toEqual([]);
  });

  test("a page with no history yet gets only the history-free checks", async () => {
    await seedAlpha(ENRICHED_PAGE.replace(/\n## Changelog[\s\S]*$/, "\n"));
    expect(await issuesFor("changelog")).toEqual([]);
  });

  test("a page kept intact by keryx writers validates clean", async () => {
    await seedAlpha(ENRICHED_PAGE);
    await wikiCollect({ cwd: root, force: true });
    expect([...(await issuesFor("changelog")), ...(await issuesFor("version")), ...(await issuesFor("metadata"))]).toEqual([]);
  });
});

describe("collect --force (AC7, AC8)", () => {
  test("AC8: an enriched draft keeps its front matter, prose and changelog; generated sections are regenerated", async () => {
    await seedAlpha(ENRICHED_PAGE);
    const result = await wikiCollect({ cwd: root, force: true });

    const alpha = result.pages.find((page) => page.path.endsWith("components/src-alpha.md"))!;
    expect(alpha.action).toBe("updated");
    const onDisk = await readFile(alphaPath(), "utf8");
    expect(onDisk).toContain("Hand-written prose about alpha that must survive every collect.");
    expect(onDisk).toContain("VerifiedAt: 1234567");
    expect(onDisk).not.toContain("stale entry from an older graph");
    expect(onDisk).toContain(ATTESTATION);
    expect(onDisk).toContain(GENERATED_ENTRY);
    expect(pageVersion(onDisk)).toBe("0.2.1");
    expect(checkPageInvariants(ENRICHED_PAGE, onDisk)).toEqual([]);
  });

  test("AC7: a page whose Version had fallen behind its changelog comes out at or above it", async () => {
    await seedAlpha(ENRICHED_PAGE.replace("Version: 0.2.0", "Version: 0.1.0"));
    await wikiCollect({ cwd: root, force: true });
    expect(pageVersion(await readFile(alphaPath(), "utf8"))).toBe("0.2.1");
  });

  test("a second collect --force over an unchanged graph changes nothing", async () => {
    await seedAlpha(ENRICHED_PAGE);
    await wikiCollect({ cwd: root, force: true });
    const first = await readFile(alphaPath(), "utf8");
    const again = await wikiCollect({ cwd: root, force: true });
    expect(again.pages.find((page) => page.path.endsWith("components/src-alpha.md"))!.action).toBe("skipped");
    expect(await readFile(alphaPath(), "utf8")).toBe(first);
  });
});
