import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { createWikiWriteContext, restoreWikiRun, writeWikiPage } from "./history";
import { findManagedBlock } from "./managed-block";
import {
  checkPageInvariants,
  mergeGeneratedSections,
  pageVersion,
  parseChangelog,
} from "./page-invariants";
import { wikiCollect, wikiValidate } from "./service";

const GENERATED_ENTRY = "- 0.1.0 - Generated by `keryx wiki collect` at 2026-09-09T11:27:38.031Z.";
const OLDEST_FIRST = [
  GENERATED_ENTRY,
  "- 0.1.1 - Expanded the module documentation.",
  "- 0.2.0 - Rewrote the overview.",
  "- 1.0.0 - Accepted after review.",
];

function modulePage(options: { version: string; changelog: string[]; reference?: string[] }): string {
  const reference = options.reference ?? ["- stale file"];
  return [
    "# Module src/pipelines",
    "",
    `Version: ${options.version}`,
    "Type: component",
    "Status: draft",
    "",
    "## Summary",
    "",
    "Pipelines.",
    "",
    "## Reference (from code graph)",
    "",
    ...reference,
    "",
    "## Related Wiki",
    "",
    "- [Wiki Index](../index.md)",
    "",
    "## Changelog",
    "",
    ...options.changelog,
    "",
  ].join("\n");
}

describe("mergeGeneratedSections keeps Version and the changelog monotonic", () => {
  test("a regenerated page continues from its newest changelog version and stays newest-first", () => {
    const existing = modulePage({ version: "0.1.0", changelog: OLDEST_FIRST });
    const generated = modulePage({ version: "0.1.0", changelog: [GENERATED_ENTRY], reference: ["- fresh file"] });

    const merged = mergeGeneratedSections(existing, generated, "Regenerated.");

    expect(pageVersion(merged)).toBe("1.0.1");
    const versions = parseChangelog(merged)!.map((entry) => entry.version);
    expect(versions).toEqual(["1.0.1", "1.0.0", "0.2.0", "0.1.1", "0.1.0"]);
    expect(checkPageInvariants(existing, merged)).toEqual([]);
  });

  test("a page whose only defect is its order is repaired without a new entry", () => {
    const existing = modulePage({ version: "0.1.0", changelog: OLDEST_FIRST });
    const generated = modulePage({ version: "0.1.0", changelog: [GENERATED_ENTRY] });

    const merged = mergeGeneratedSections(existing, generated, "Regenerated.");

    expect(pageVersion(merged)).toBe("1.0.0");
    expect(parseChangelog(merged)!.map((entry) => entry.version)).toEqual(["1.0.0", "0.2.0", "0.1.1", "0.1.0"]);
    expect(checkPageInvariants(existing, merged)).toEqual([]);
  });

  test("a healthy page nothing differs on is returned as it was", () => {
    const existing = modulePage({ version: "1.0.0", changelog: [...OLDEST_FIRST].reverse() });
    const generated = modulePage({ version: "0.1.0", changelog: [GENERATED_ENTRY] });

    expect(mergeGeneratedSections(existing, generated, "Regenerated.")).toBe(existing);
  });

  test("a hand-named Reference section beside the generated one does not make the block malformed", () => {
    const existing = modulePage({ version: "1.0.0", changelog: [...OLDEST_FIRST].reverse() }).replace(
      "## Reference (from code graph)\n\n- stale file",
      "## Reference categories\n\nHand-written prose.",
    );
    const generated = modulePage({ version: "0.1.0", changelog: [GENERATED_ENTRY], reference: ["- fresh file"] });

    const merged = mergeGeneratedSections(existing, generated, "Regenerated.");

    expect(merged).toContain("## Reference categories\n\nHand-written prose.");
    expect(merged).toContain("## Reference (from code graph)\n\n- fresh file");
    expect(findManagedBlock(merged).kind).not.toBe("malformed");

    const again = mergeGeneratedSections(merged, generated, "Regenerated.");
    expect(again.match(/^## Reference \(from code graph\)/gm)).toHaveLength(1);
  });
});

describe("wiki collect after wiki restore", () => {
  let root: string;
  let clock: number;

  beforeEach(async () => {
    root = await mkdtemp(path.join(tmpdir(), "keryx-wiki-monotonic-"));
    clock = Date.parse("2026-10-01T10:00:00.000Z");
    const graphDir = path.join(root, ".metaproject", "data", "gdgraph", "storage");
    await mkdir(graphDir, { recursive: true });
    await writeFile(
      path.join(graphDir, "nodes.jsonl"),
      ["src/pipelines/a.ts", "src/pipelines/b.ts", "src/pipelines/c.ts"]
        .map((file) => JSON.stringify({ id: file, kind: "file", path: file }))
        .join("\n"),
      "utf8",
    );
    await writeFile(path.join(graphDir, "edges.jsonl"), "", "utf8");
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  function run(command: string) {
    return createWikiWriteContext(root, command, { now: () => new Date((clock += 1000)) });
  }

  async function lifecycleIssues(): Promise<string[]> {
    const result = await wikiValidate(root);
    return result.issues
      .filter((issue) => ["changelog", "version", "managed-block"].includes(issue.kind))
      .map((issue) => `${issue.kind}: ${issue.page}: ${issue.message}`);
  }

  test("restoring an older page and collecting leaves the page valid", async () => {
    const page = path.join(root, ".metaproject", "wiki", "components", "src-pipelines.md");
    await mkdir(path.dirname(page), { recursive: true });

    const older = modulePage({ version: "0.1.0", changelog: OLDEST_FIRST });
    await writeWikiPage(run("wiki enrich"), page, older);
    const newer = run("wiki enrich");
    await writeWikiPage(newer, page, modulePage({ version: "1.0.0", changelog: [...OLDEST_FIRST].reverse() }));
    await restoreWikiRun(run("wiki restore"), newer.runId);
    expect(await readFile(page, "utf8")).toBe(older);

    await wikiCollect({ cwd: root, force: true });

    const collected = await readFile(page, "utf8");
    expect(pageVersion(collected)).toBe("1.0.1");
    expect(parseChangelog(collected)![0]!.version).toBe("1.0.1");
    expect(await lifecycleIssues()).toEqual([]);
  });
});
