// The wire contract between a running shell and `keryx serve` (flow 376, block 2).
//
// One module both ends import, so the server surface and the client library cannot
// drift: route paths, body limits, id shapes and the SSE event payloads live here
// and nowhere else. Nothing in this file does I/O.
//
// Auth is NOT in here. These routes are reached with the local shell token, a
// secret separate from the serve bearer; see `shell-token.ts` and the header of
// `lib/serve-server.ts`.

export const REMOTE_API_PREFIX = "/v1/remote";
export const REMOTE_SCHEMA_VERSION = "1.0.0";

export type RemoteRoute = "register" | "deregister" | "heartbeat" | "reply" | "approval" | "ack" | "stream";

export const REMOTE_ROUTE_METHODS: Readonly<Record<RemoteRoute, "GET" | "POST">> = {
  register: "POST",
  deregister: "POST",
  heartbeat: "POST",
  reply: "POST",
  approval: "POST",
  ack: "POST",
  stream: "GET",
};

export function remoteRoutePath(route: RemoteRoute): string {
  return `${REMOTE_API_PREFIX}/${route}`;
}

/** Every body is small: a line, a reply, a prompt. Bigger is refused before it is parsed. */
export const MAX_REMOTE_BODY_BYTES = 64 * 1024;
export const MAX_PROJECT_CHARS = 256;
export const MAX_APPROVAL_PROMPT_CHARS = 3_000;
export const MAX_KEYBOARD_ROWS = 8;
export const MAX_KEYBOARD_BUTTONS_PER_ROW = 8;
export const MAX_BUTTON_TEXT_CHARS = 64;
/** Telegram's own limit on `callback_data`. */
export const MAX_CALLBACK_DATA_BYTES = 64;

/** How long an approval stays answerable when the shell names no timeout, and the most it may name. */
export const DEFAULT_APPROVAL_TIMEOUT_MS = 5 * 60_000;
export const MAX_APPROVAL_TIMEOUT_MS = 60 * 60_000;
export const MIN_APPROVAL_TIMEOUT_MS = 100;

/** Server comment line on an otherwise idle stream; keeps proxies and the client's own watchdog honest. */
export const DEFAULT_KEEPALIVE_MS = 15_000;
/** How long the server waits for the shell to acknowledge a delivered line before treating it as undelivered. */
export const DEFAULT_ACK_TIMEOUT_MS = 30_000;

/**
 * A session id is chosen by the shell. Structural, never "starts with": it becomes
 * a registry key and appears in query strings, so it is a short token of a closed
 * alphabet that cannot carry a path, a space, a control character or a delimiter.
 */
export const SESSION_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;

export function isSessionId(value: unknown): value is string {
  return typeof value === "string" && SESSION_ID_PATTERN.test(value);
}

/** An approval id is generated by the server: "ap" and twelve lowercase hex characters. */
export const APPROVAL_ID_PATTERN = /^ap[0-9a-f]{12}$/;

export function isApprovalId(value: unknown): value is string {
  return typeof value === "string" && APPROVAL_ID_PATTERN.test(value);
}

/** `ap:<id>:allow` / `ap:<id>:deny`: 20 bytes at most, inside Telegram's 64. */
const APPROVAL_CALLBACK_PATTERN = /^ap:(ap[0-9a-f]{12}):(allow|deny)$/;

export function approvalCallbackData(approvalId: string, decision: ApprovalDecision): string {
  return `ap:${approvalId}:${decision}`;
}

export function parseApprovalCallback(data: string): { approvalId: string; decision: ApprovalDecision } | undefined {
  const match = APPROVAL_CALLBACK_PATTERN.exec(data);
  if (match === null) {
    return undefined;
  }
  return { approvalId: match[1] as string, decision: match[2] as ApprovalDecision };
}

/** Buttons a shell may attach to a reply may not collide with the approval namespace. */
export const RESERVED_CALLBACK_PREFIX = "ap:";

export type ApprovalDecision = "allow" | "deny";

// ---- request bodies -----------------------------------------------------------

export interface RegisterBody {
  sessionId: string;
  project: string;
  name?: string;
}

export interface SessionBody {
  sessionId: string;
}

export interface ReplyButton {
  text: string;
  data: string;
}

export interface ReplyBody {
  sessionId: string;
  text: string;
  keyboard?: ReplyButton[][];
}

export interface ApprovalBody {
  sessionId: string;
  prompt: string;
  timeoutMs?: number;
}

export interface AckBody {
  sessionId: string;
  updateId: number;
}

// ---- responses ----------------------------------------------------------------

export interface RegisterResponse {
  schemaVersion: string;
  name: string;
  threadId: number;
  reused: boolean;
  /** How long a run started from Telegram may take before the shell interrupts it. */
  runTimeoutMs: number;
}

export interface HeartbeatResponse {
  schemaVersion: string;
  name: string;
  threadId: number;
}

export interface ApprovalResponse {
  schemaVersion: string;
  approvalId: string;
  /** Epoch ms after which the server drops a late press instead of delivering it. */
  expiresAt: number;
}

// ---- the stream ---------------------------------------------------------------
//
// `GET /v1/remote/stream?sessionId=<id>` answers `text/event-stream`. Each frame is
//
//   event: <inbound|approval|callback|status>
//   id: <update id>            (inbound, approval, callback only)
//   data: <one line of JSON>
//
// plus a `: keepalive` comment line every `keepaliveMs`. The `id` is the Telegram
// update id; `Last-Event-ID` on a reconnect means "I have COMPLETED everything up
// to and including this id" (a cumulative acknowledgement), so the server does not
// resend those. A line is acknowledged separately with `POST /v1/remote/ack` after
// the shell has finished handling it.

export interface InboundEvent {
  updateId: number;
  text: string;
  threadId: number;
  fromId: number;
  receivedAt: number;
}

export interface ApprovalEvent {
  updateId: number;
  approvalId: string;
  decision: ApprovalDecision;
}

export interface CallbackEvent {
  updateId: number;
  data: string;
  threadId: number;
  fromId: number;
  messageId?: number;
}

export type StatusKind = "ready" | "superseded" | "closing";

export interface StatusEvent {
  kind: StatusKind;
  name?: string;
  threadId?: number;
}

export type StreamEventName = "inbound" | "approval" | "callback" | "status";

export function encodeSseEvent(name: StreamEventName, data: unknown, id?: number): string {
  // `JSON.stringify` never emits a raw newline, so one `data:` line is enough.
  return `event: ${name}\n${id === undefined ? "" : `id: ${id}\n`}data: ${JSON.stringify(data)}\n\n`;
}

export const SSE_KEEPALIVE_FRAME = ": keepalive\n\n";

export interface ParsedSseFrame {
  event: string;
  id?: string;
  data: string;
}

/**
 * Incremental SSE parser: feed text chunks, get completed frames. Comment lines
 * (leading ":") and frames with no data are dropped. Tolerates CRLF.
 */
export class SseParser {
  private buffer = "";

  push(chunk: string): ParsedSseFrame[] {
    this.buffer += chunk;
    const frames: ParsedSseFrame[] = [];
    for (;;) {
      const match = /\r?\n\r?\n/.exec(this.buffer);
      if (match === null) {
        break;
      }
      const block = this.buffer.slice(0, match.index);
      this.buffer = this.buffer.slice(match.index + match[0].length);
      let event = "message";
      let id: string | undefined;
      const data: string[] = [];
      for (const line of block.split(/\r?\n/)) {
        if (line.length === 0 || line.startsWith(":")) {
          continue;
        }
        const colon = line.indexOf(":");
        const field = colon < 0 ? line : line.slice(0, colon);
        let value = colon < 0 ? "" : line.slice(colon + 1);
        if (value.startsWith(" ")) {
          value = value.slice(1);
        }
        if (field === "event") {
          event = value;
        } else if (field === "id") {
          id = value;
        } else if (field === "data") {
          data.push(value);
        }
      }
      if (data.length > 0) {
        frames.push({ event, ...(id === undefined ? {} : { id }), data: data.join("\n") });
      }
    }
    return frames;
  }
}
